//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PfizerKidsLab
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pfizerKidsHomeEntities : DbContext
    {
        public pfizerKidsHomeEntities()
            : base("name=pfizerKidsHomeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<auxiliar> auxiliar { get; set; }
        public virtual DbSet<citaVacuna> citaVacuna { get; set; }
        public virtual DbSet<infante> infante { get; set; }
        public virtual DbSet<persona> persona { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<vacuna> vacuna { get; set; }
    }
}
